services:
  postgres:
    image: postgres:15
    container_name: booking-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: booking_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
